services:
  backend:
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./src:/service/src

  db:
    ports:
      - "5433:5432"
